version: "3"
services:
  postgresdb:
    image: postgres:latest
    container_name: psqldb
    environment:
      - POSTGRES_PASSWORD=gGnBe7HwwT!37ER
      - POSTGRES_DB=painelcovid
    volumes:
      - "./psqldata/:/var/lib/postgresql/data"
    ports:
      - "5432:5432"